/**
 * Reads every spec under specs/rest, specs/rpc/l1, specs/rpc/evm/generated and:
 *
 *   1. Writes one real file per method: pages/api-reference/{category}/{method}.tsx
 *      A tiny stub that imports RpcMethod/RestMethod and inlines that method's data —
 *      this is what "методы лежат строго по папочкам с сетями" means in practice:
 *      real files, real folders, real Next.js routing, no virtual catch-all route.
 *   2. Writes pages/api-reference/{category}/_meta.json (method name -> title) so
 *      Nextra's own pageMap, breadcrumbs, and prev/next links work correctly even
 *      though the *visual* sidebar for this section is fully custom.
 *   3. Rewrites pages/api-reference/_meta.json to list every category as hidden
 *      (they're reachable through the custom NetworkSelector, not the default tree).
 *   4. Writes pages/api-reference/nav.generated.json, the flat list every custom
 *      sidebar component (NetworkSelector, MethodSidebarList, ApiReferenceWelcome)
 *      reads to build its UI.
 *
 * Each category folder is wiped and rewritten from scratch on every run — these
 * folders are 100% generated output, never hand-edited. Run with `yarn generate:pages`
 * (or `yarn generate:all`, which runs the EVM filter step first).
 */
import fs from "node:fs";
import path from "node:path";
import yaml from "js-yaml";
import type { OpenApiLikeDoc, OpenRpcLikeDoc, RestOperationDef, RpcMethodDef } from "../lib/types";

const ROOT = path.resolve(__dirname, "..");
const API_REF_DIR = path.join(ROOT, "pages/api-reference");
const ENDPOINTS_PATH = path.join(ROOT, "data/endpoints.yaml");

interface NavEntry {
  kind: "rest" | "rpc-l1" | "rpc-evm";
  category: string;
  methodName: string;
  specPath: string;
  slug: string[];
}

function readJson<T>(p: string): T {
  return JSON.parse(fs.readFileSync(p, "utf-8")) as T;
}

function listFiles(dir: string, suffix: string): string[] {
  if (!fs.existsSync(dir)) return [];
  return fs
    .readdirSync(dir)
    .filter((f) => f.endsWith(suffix) && !f.startsWith("_"))
    .map((f) => path.join(dir, f));
}

function loadEndpoints(): Record<string, string> {
  return (yaml.load(fs.readFileSync(ENDPOINTS_PATH, "utf-8")) as Record<string, string>) ?? {};
}

/** A JS object literal is valid to `JSON.stringify` straight into source — no need for a JSON.parse call at runtime. */
function toObjectLiteral(value: unknown): string {
  return JSON.stringify(value, null, 2);
}

function relativeImportTo(fromFile: string, toFile: string): string {
  let rel = path.relative(path.dirname(fromFile), toFile).replace(/\\/g, "/").replace(/\.tsx?$/, "");
  if (!rel.startsWith(".")) rel = `./${rel}`;
  return rel;
}

function writeRpcStub(outFile: string, method: RpcMethodDef, endpoint: string) {
  const componentImport = relativeImportTo(outFile, path.join(ROOT, "components/RpcMethod.tsx"));
  const content = `import { RpcMethod } from "${componentImport}";
import type { RpcMethodDef } from "${relativeImportTo(outFile, path.join(ROOT, "lib/types.ts"))}";

// Generated by generators/generate-pages.ts — do not edit by hand.
// Edit the source method in specs/rpc/.../_base-methods.openrpc.json (EVM) or the
// relevant specs/rpc/l1/*.openrpc.json (L1), then re-run \`yarn generate:all\`.
const method: RpcMethodDef = ${toObjectLiteral(method)};

export default function Page() {
  return <RpcMethod method={method} endpoint="${endpoint}" />;
}
`;
  fs.writeFileSync(outFile, content);
}

function writeRestStub(outFile: string, operation: RestOperationDef, baseUrl: string) {
  const componentImport = relativeImportTo(outFile, path.join(ROOT, "components/RestMethod.tsx"));
  const content = `import { RestMethod } from "${componentImport}";
import type { RestOperationDef } from "${relativeImportTo(outFile, path.join(ROOT, "lib/types.ts"))}";

// Generated by generators/generate-pages.ts — do not edit by hand.
// Edit the source operation in specs/rest/*.openapi.json, then re-run \`yarn generate:all\`.
const operation: RestOperationDef = ${toObjectLiteral(operation)};

export default function Page() {
  return <RestMethod operation={operation} baseUrl="${baseUrl}" />;
}
`;
  fs.writeFileSync(outFile, content);
}

function writeCategoryOverviewStub(dir: string) {
  const outFile = path.join(dir, "index.tsx");
  const componentImport = relativeImportTo(outFile, path.join(ROOT, "components/CategoryOverview.tsx"));
  const content = `import { CategoryOverview } from "${componentImport}";

// Generated by generators/generate-pages.ts — do not edit by hand.
export default function Page() {
  return <CategoryOverview />;
}
`;
  fs.writeFileSync(outFile, content);
}

function generate() {
  const endpoints = loadEndpoints();
  const entries: NavEntry[] = [];
  const categoriesTouched = new Set<string>();

  // --- REST ---
  for (const file of listFiles(path.join(ROOT, "specs/rest"), ".openapi.json")) {
    const doc = readJson<OpenApiLikeDoc>(file);
    const category = path.basename(file).replace(".openapi.json", "");
    const dir = path.join(API_REF_DIR, category);
    fs.rmSync(dir, { recursive: true, force: true });
    fs.mkdirSync(dir, { recursive: true });
    categoriesTouched.add(category);

    const meta: Record<string, string> = {};
    for (const op of doc.operations) {
      const outFile = path.join(dir, `${op.name}.tsx`);
      writeRestStub(outFile, op, endpoints[category] ?? doc.servers[0]?.url ?? "");
      meta[op.name] = op.name;
      entries.push({ kind: "rest", category, methodName: op.name, specPath: path.relative(ROOT, file), slug: ["api-reference", category, op.name] });
    }
    fs.writeFileSync(path.join(dir, "_meta.json"), JSON.stringify(meta, null, 2) + "\n");
    writeCategoryOverviewStub(dir);
  }

  // --- L1 RPC ---
  for (const file of listFiles(path.join(ROOT, "specs/rpc/l1"), ".openrpc.json")) {
    const doc = readJson<OpenRpcLikeDoc>(file);
    const category = `${doc.network}-api`;
    const dir = path.join(API_REF_DIR, category);
    fs.rmSync(dir, { recursive: true, force: true });
    fs.mkdirSync(dir, { recursive: true });
    categoriesTouched.add(category);

    const meta: Record<string, string> = {};
    for (const m of doc.methods) {
      const outFile = path.join(dir, `${m.name}.tsx`);
      writeRpcStub(outFile, m, endpoints[category] ?? "");
      meta[m.name] = m.name;
      entries.push({ kind: "rpc-l1", category, methodName: m.name, specPath: path.relative(ROOT, file), slug: ["api-reference", category, m.name] });
    }
    fs.writeFileSync(path.join(dir, "_meta.json"), JSON.stringify(meta, null, 2) + "\n");
    writeCategoryOverviewStub(dir);
  }

  // --- EVM RPC (generated per-network specs) ---
  for (const file of listFiles(path.join(ROOT, "specs/rpc/evm/generated"), ".openrpc.json")) {
    const doc = readJson<OpenRpcLikeDoc>(file);
    const category = `${doc.network}-api`;
    const dir = path.join(API_REF_DIR, category);
    fs.rmSync(dir, { recursive: true, force: true });
    fs.mkdirSync(dir, { recursive: true });
    categoriesTouched.add(category);

    const meta: Record<string, string> = {};
    for (const m of doc.methods) {
      const outFile = path.join(dir, `${m.name}.tsx`);
      writeRpcStub(outFile, m, endpoints[category] ?? "");
      meta[m.name] = m.name;
      entries.push({ kind: "rpc-evm", category, methodName: m.name, specPath: path.relative(ROOT, file), slug: ["api-reference", category, m.name] });
    }
    fs.writeFileSync(path.join(dir, "_meta.json"), JSON.stringify(meta, null, 2) + "\n");
    writeCategoryOverviewStub(dir);
  }

  // --- Parent _meta.json: index + every category folder hidden from the native tree ---
  const parentMeta: Record<string, unknown> = { index: "Welcome" };
  for (const category of Array.from(categoriesTouched).sort()) {
    parentMeta[category] = { display: "hidden" };
  }
  fs.writeFileSync(path.join(API_REF_DIR, "_meta.json"), JSON.stringify(parentMeta, null, 2) + "\n");

  // --- nav.generated.json: the flat list every custom sidebar component reads ---
  fs.writeFileSync(path.join(API_REF_DIR, "nav.generated.json"), JSON.stringify(entries, null, 2) + "\n");

  console.log(`✔ Generated ${entries.length} method page(s) across ${categoriesTouched.size} categor${categoriesTouched.size === 1 ? "y" : "ies"}:`);
  for (const category of Array.from(categoriesTouched).sort()) {
    console.log(`  - ${category}: ${entries.filter((e) => e.category === category).length} method(s)`);
  }
}

generate();
