import { RpcMethod } from "../../../components/RpcMethod";
import type { RpcMethodDef } from "../../../lib/types";

// Generated by generators/generate-pages.ts — do not edit by hand.
// Edit the source method in specs/rpc/.../_base-methods.openrpc.json (EVM) or the
// relevant specs/rpc/l1/*.openrpc.json (L1), then re-run `yarn generate:all`.
const method: RpcMethodDef = {
  "name": "debug_traceBlockByHash",
  "description": "Traces the execution of all transactions in a block specified by its hash, providing detailed execution traces.",
  "cu": 20,
  "useCases": [
    "Trace execution paths for transactions in specific block",
    "Debug contract interactions within a given block",
    "Analyze gas usage for transactions in specific block"
  ],
  "constraints": [
    "Available only on paid tier",
    "Traces may include large data sets for complex blocks",
    "Potential delays due to high processing requirements"
  ],
  "params": [
    {
      "paramName": "blockHash",
      "type": "string",
      "paramDescription": "The hash of the block to be traced."
    },
    {
      "paramName": "tracer",
      "type": "object",
      "paramDescription": "Supports callTracer and prestateTracer for detailed trace analysis.",
      "childrenParamsType": "object",
      "childrenParams": [
        {
          "paramName": "tracer",
          "type": "string",
          "paramDescription": "Default: callTracer"
        },
        {
          "paramName": "tracerConfig",
          "type": "object",
          "childrenParamsType": "boolean",
          "childrenParams": [
            {
              "paramName": "onlyTopCall",
              "type": "boolean"
            }
          ]
        }
      ]
    }
  ],
  "result": {
    "paramName": "result",
    "type": "array_of_objects",
    "paramDescription": "Array of block traces.",
    "childrenParamsType": "object",
    "childrenParams": [
      {
        "paramName": "callTracer",
        "type": "object",
        "childrenParamsType": "object",
        "childrenParams": [
          {
            "paramName": "from",
            "type": "string",
            "paramDescription": "Sender's address."
          },
          {
            "paramName": "to",
            "type": "string",
            "paramDescription": "Receiver's address."
          },
          {
            "paramName": "value",
            "type": "string",
            "paramDescription": "Amount transferred in wei."
          },
          {
            "paramName": "gas",
            "type": "string",
            "paramDescription": "Gas allocated for the call."
          },
          {
            "paramName": "input",
            "type": "string",
            "paramDescription": "Data sent with the call."
          },
          {
            "paramName": "gasUsed",
            "type": "string",
            "paramDescription": "Gas consumed by the trace."
          },
          {
            "paramName": "output",
            "type": "string",
            "paramDescription": "Result of the call."
          },
          {
            "paramName": "error",
            "type": "string",
            "paramDescription": "Any error encountered."
          },
          {
            "paramName": "revertReason",
            "type": "string",
            "paramDescription": "Solidity revert reason, if any."
          },
          {
            "paramName": "calls",
            "type": "array",
            "paramDescription": "list of sub-calls"
          }
        ]
      },
      {
        "paramName": "prestateTracer",
        "type": "object",
        "childrenParamsType": "object",
        "childrenParams": [
          {
            "paramName": "balance",
            "type": "string",
            "paramDescription": "Account balance in wei."
          },
          {
            "paramName": "nonce",
            "type": "uint64",
            "paramDescription": "The transaction count for the account."
          },
          {
            "paramName": "code",
            "type": "string",
            "paramDescription": "Hex-encoded contract bytecode."
          },
          {
            "paramName": "storage",
            "type": "map[string]string",
            "paramDescription": "Contract's storage slots."
          }
        ]
      }
    ]
  },
  "examples": {
    "request": {
      "jsonrpc": "2.0",
      "method": "debug_traceBlockByHash",
      "params": [
        "0x97b49e43632ac70c46b4003434058b18db0ad809617bd29f3448d46ca9085576",
        {
          "tracer": "callTracer"
        }
      ],
      "id": 1
    }
  },
  "networks": [
    "ethereum"
  ]
};

export default function Page() {
  return <RpcMethod method={method} endpoint="https://lb.drpc.org/ogrpc?network=ethereum" />;
}
