import { CategoryOverview } from "../../../components/CategoryOverview";

// Generated by generators/generate-pages.ts — do not edit by hand.
export default function Page() {
  return <CategoryOverview />;
}
