import { RpcMethod } from "../../../components/RpcMethod";
import type { RpcMethodDef } from "../../../lib/types";

// Generated by generators/generate-pages.ts — do not edit by hand.
// Edit the source method in specs/rpc/.../_base-methods.openrpc.json (EVM) or the
// relevant specs/rpc/l1/*.openrpc.json (L1), then re-run `yarn generate:all`.
const method: RpcMethodDef = {
  "name": "eth_getBalance",
  "description": "Returns the balance of the account of given address.",
  "cu": 10,
  "useCases": [
    "Check wallet balances",
    "Verify funds before a transaction"
  ],
  "constraints": [],
  "params": [
    {
      "paramName": "address",
      "type": "string",
      "paramDescription": "Address to check for balance."
    },
    {
      "paramName": "blockTag",
      "type": "string",
      "paramDescription": "Block number or tag, e.g. 'latest'."
    }
  ],
  "result": {
    "paramName": "result",
    "type": "string",
    "paramDescription": "Integer of the current balance in wei."
  },
  "examples": {
    "request": {
      "jsonrpc": "2.0",
      "method": "eth_getBalance",
      "params": [
        "0x...",
        "latest"
      ],
      "id": 1
    }
  },
  "networks": [
    "polygon"
  ]
};

export default function Page() {
  return <RpcMethod method={method} endpoint="https://lb.drpc.org/ogrpc?network=polygon" />;
}
