import { RpcMethod } from "../../../components/RpcMethod";
import type { RpcMethodDef } from "../../../lib/types";

// Generated by generators/generate-pages.ts — do not edit by hand.
// Edit the source method in specs/rpc/.../_base-methods.openrpc.json (EVM) or the
// relevant specs/rpc/l1/*.openrpc.json (L1), then re-run `yarn generate:all`.
const method: RpcMethodDef = {
  "name": "eth_blockNumber",
  "description": "Returns the number of the most recent block.",
  "cu": 5,
  "useCases": [
    "Poll chain head",
    "Determine confirmation depth"
  ],
  "constraints": [],
  "params": [],
  "result": {
    "paramName": "result",
    "type": "string",
    "paramDescription": "Integer of the current block number."
  },
  "examples": {
    "request": {
      "jsonrpc": "2.0",
      "method": "eth_blockNumber",
      "params": [],
      "id": 1
    }
  },
  "networks": [
    "polygon"
  ]
};

export default function Page() {
  return <RpcMethod method={method} endpoint="https://lb.drpc.org/ogrpc?network=polygon" />;
}
