import { RpcMethod } from "../../../components/RpcMethod";
import type { RpcMethodDef } from "../../../lib/types";

// Generated by generators/generate-pages.ts — do not edit by hand.
// Edit the source method in specs/rpc/.../_base-methods.openrpc.json (EVM) or the
// relevant specs/rpc/l1/*.openrpc.json (L1), then re-run `yarn generate:all`.
const method: RpcMethodDef = {
  "name": "eth_call",
  "description": "Executes a new message call immediately without creating a transaction on the blockchain.",
  "cu": 20,
  "useCases": [
    "Simulate contract calls before sending a transaction",
    "Read on-chain state without gas cost"
  ],
  "constraints": [
    "Does not modify blockchain state"
  ],
  "params": [
    {
      "paramName": "transaction",
      "type": "object",
      "paramDescription": "The transaction call object.",
      "childrenParamsType": "string",
      "childrenParams": [
        {
          "paramName": "to",
          "type": "string",
          "paramDescription": "Address the transaction is directed to."
        },
        {
          "paramName": "data",
          "type": "string",
          "paramDescription": "Hash of the method signature and encoded parameters."
        }
      ]
    },
    {
      "paramName": "blockTag",
      "type": "string",
      "paramDescription": "Block number or tag, e.g. 'latest'."
    }
  ],
  "result": {
    "paramName": "result",
    "type": "string",
    "paramDescription": "The return value of the executed contract call."
  },
  "examples": {
    "request": {
      "jsonrpc": "2.0",
      "method": "eth_call",
      "params": [
        {
          "to": "0x...",
          "data": "0x..."
        },
        "latest"
      ],
      "id": 1
    }
  },
  "networks": [
    "polygon"
  ]
};

export default function Page() {
  return <RpcMethod method={method} endpoint="https://lb.drpc.org/ogrpc?network=polygon" />;
}
